### ISSUE TITLE
Unable To Use Find Match or Leave Party When Using

### ISSUE THREAD

**Issue by Kyrluckechuck** [nicoco007/LoL-Auto-Login#24] opened 2019-03-25 22:24 UTC
This seems to be a weird issue, possibly introduced by a later version of the client (9.6-13536046.13535937), but it would appear that using this system does not let you use those buttons anymore for some reason. 

Possibly client resolution-related, however, it appears every time I use the auto-login method. Shift-launching it results in those buttons being clickable as usual.

For reference, attached is a screenshot of the buttons in question:
![image](https://user-images.githubusercontent.com/7606153/54958055-e6bede80-4f2a-11e9-8acb-5584fb0a3918.png)

You'll also notice that it's not detecting them as a button, whereas something like this is:
![image](https://user-images.githubusercontent.com/7606153/54958079-f5a59100-4f2a-11e9-946f-ee296b5a34f8.png)

Lastly, attached are the logs (though I'm not sure they will be of much help here).
[2019-03-25T18-13-01_LoLAutoLogin.log](https://github.com/nicoco007/LoL-Auto-Login/files/3005751/2019-03-25T18-13-01_LoLAutoLogin.log)

Happy to test whatever changes or client changes that may help, I just have no idea what!

Additionally, (unsure if related), the bar across the top (Play, Collection, Store, etc) loads twice, with the SFX going twice, too.

**Comment by nicoco007** [comment] 2019-04-06 22:46
Huh, that's a weird one. I'll take a look as soon as possible.

**Comment by nicoco007** [comment] 2019-04-16 01:34
Unfortunately I can't reproduce the issue on my end with client version 9.7-18446127.18445799.

What made you say "possibly client resolution-related" ? Does it only happen when the client is running at certain resolutions? Does it happen every single time you try to launch through LoL Auto Login or does it sometimes work properly? Have you tried focusing another window and bringing focus back to the client?

**Comment by Kyrluckechuck** [comment] 2019-04-16 03:14
Interesting, what is very odd about this is that with the latest patch, I am unable to reproduce it either! (though the triple GFX glitch across the top still happens, it's purely aesthetic though)

To answer your questions, though, I had been using the non-default resolution for my computer for the client in order to have a bit smaller of a client, the 1280x720 window size. I was thinking maybe that had some sort of effect on the offsets, but it seems to no longer be the case.

Additionally yes, it was every single time it was launched, but every time using the regular client worked without problem. Lastly, no, switching window focus away and back didn't have any sort of effect either, but regardless it is working now.

Tentatively this should be closed since it can't be reproduced, but I'll try re-open if at some point it returns for whatever reason!

**Comment by medhefgo** [comment] 2019-04-16 08:25
This is still happening for me most of the times. I found that if I start the regular client and wait for the login background image/video to fully load and then start auto login things work again. It will then also not do the triple GFX thingy, which makes the client waaaay less laggy.

It's probably a very racy loading issue so I'd say the best solution might be to find a way to delay auto login until the background imagery is fully loaded up. At the very minimum we'd need a config option to delay login for some (milli)seconds.

**Comment by nicoco007** [comment] 2019-04-16 14:23
Ah, that makes sense. I'll see what I can do about it.

**Comment by nicoco007** [comment] 2019-04-16 22:49
Could you try [this build](https://github.com/nicoco007/LoL-Auto-Login/files/3087182/LoLAutoLogin.zip)? If it doesn't work, could you also try adding `  wait-for-ui: Full` (with 2 preceding spaces) in `Config/LoLAutoLoginSettings.yaml` under `login-detection` ?

**Comment by medhefgo** [comment] 2019-04-17 08:10
It's still happening with or without wait-for-ui. Funnily enough, if I set debug to true, it seems to work regardless of the wait-for-ui setting.

**Comment by nicoco007** [comment] 2019-04-17 12:22
I guess that makes sense since enabling debug does slow down the process slightly, but I wouldn't have expected it to make that much of a difference.

When you put `wait-for-ui: Full`, did it wait until the login animation loaded fully before entering your password or did behavior stay the same as before?

**Comment by medhefgo** [comment] 2019-04-17 13:57
I'd say it does wait for the image/video to load up, but it's going so fast it barely makes a difference.

**Comment by nicoco007** [comment] 2019-04-26 14:44
I think I'll just do what @medhefgo suggested and add a user-configurable delay since there doesn't seem to be a surefire way of knowing that the launcher is fully loaded. That should hopefully be done and released within a week.

**Comment by nicoco007** [comment] 2019-05-21 03:20
Could either/both of you try out [this build](https://ci.gnyra.com/job/LoL-Auto-Login/job/delay/1/artifact/publish/LoLAutoLogin-delay-1-setup.zip)? There's once again a new setting in `Config/LoLAutoLoginSettings.yaml` called `delay` which is 500 milliseconds by default but you change it to any number.

**Comment by medhefgo** [comment] 2019-05-21 07:42
I just tested this on a different computer that is fairly slow compared to my normal one that also has these issues. Some login attempts start working at around 250ms and it stops reliably at 650ms at which point the secondary issue with the triple sound effects stops too. So I'd suggest putting the default at 750ms for safety.

While I'm here: could you save the current cursor position before warping it to the login button and after the click move it back to the original location? Jumping cursors are really annoying and unnecessary when there's such an easy way to fix that.

**Comment by Kyrluckechuck** [comment] 2019-05-21 16:18
I haven't had much free time to test, but thanks for doing that @medhefgo ! 

I second the mouse cursor relocation if possible!

**Comment by nicoco007** [comment] 2019-05-25 19:38
I've made some mouse changes in [this build](https://ci.gnyra.com/job/LoL-Auto-Login/job/feature%252Fno-cursor-move/3/artifact/publish/LoLAutoLogin-setup.zip), could you try it out?

**Comment by medhefgo** [comment] 2019-05-25 19:52
Seems to be working.

**Comment by nicoco007** [comment] 2019-06-01 02:30
Great! I'll close this issue for now. The fix will be included in version 2.1.1; if the problem comes back, feel free to reopen this issue or create a new one!

**Closed as completed** 2019-06-01 02:30 UTC
Labels: bug
